# General
title:                "Staticaly"

# A simple tagline: Make it Static!
tagline:              >-
    A free CDN for Git repositories, WordPress, images and more

# Define description for the site
description:          >-
    Staticaly is a free CDN for Git repositories, WordPress, images and other assets with high-performance of caching and optimization.

# Also used for SEO Tag
logo:                 "/static/images/staticaly_wide.svg"
lang:                 "en_US"

# Set URL
url:                  "https://www.staticaly.com"

encoding:             "UTF-8"
permalink:            /:title
highlighter:          rouge
version:              0.1
year:                 2018

# Utilities
future:               true
jailed:               false
gfm_quirks:           paragraph_end

repo:                 "https://github.com/marsble/staticaly"

# Staticaly
staticaly:
    devs_url:         "https://developers.marsble.com"
    datacenter_num:   165+
    main_cdn:         "CloudFlare, Fastly, CDN77, and BunnyCDN"
    newsletter_url:  >-
        https://marsble.us18.list-manage.com/subscribe/post?u=4dfd4ae04677bf4f6248182fc&amp;id=397ea962f2

# Analytics
marsble:
    username:         staticaly
    analytics_url:    "https://pixel.marsble.com"
    analytics_id:     "921b301945cfd2a048e13a9d1a1b67a86be4b8c8"

# Google
google:
    analytics_id:     "UA-74801412-7"

# Social
social:
    name:             "Staticaly"
    links:
      - https://www.marsble.com/u/staticaly
      - https://twitter.com/staticalyhq
      - https://www.instagram.com/staticalyhq
      - https://github.com/staticaly

# Twitter
twitter:
    username:         staticalyhq

# Instagram
instagram:
    username:         staticalyhq

# GitHub
github_username:      marsble/staticaly

# The author
author:
    twitter:          fransallen

# Default image for socmed
defaults:
  - scope:
      path:           "/static/images"
    values:
      image:          "/staticaly_icon_bg_dark_lg.png"

# Static files
cdn:
    domain:           "cdn.staticaly.com"
    url:              "https://cdn.staticaly.com"
    imgpx_domain:     "cdn.staticaly.com/img"
    imgpx_url:        "https://cdn.staticaly.com/img"
    favicons_domain:  "cdn.staticaly.com/favicons"
    favicons_url:     "https://cdn.staticaly.com/favicons"
    badge_domain:     "cdn.staticaly.com/badges"
    badge_url:        "https://cdn.staticaly.com/badges"
    static:           "/static"

sass:
    sass_dir:         "./static/css"
    style:            compressed

# Include to public directory
include:
    - "_headers"
    - "_pages"
    - "_redirects"
    - "_redirections"

# Exclude from public directory
exclude:
    - "scripts"
    - "vendor"

kramdown:
    input:            GFM
    hard_wrap:        false

# Plugins
plugins:
    - jekyll-coffeescript
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    #- jekyll-minifier

#jekyll-minifier:
    #remove_https_protocol: true
    #exclude:
        #- "static/js/app.js"
        #- "src/lambda/hello.js"
